version: '3.8'

services:
  api-server:
    build: .
    container_name: code-executor-api
    ports:
      - "3000:3000"
    volumes:
      # Expose host's Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=3000
      - NODE_ENV=production
      - REDIS_HOST=promoted-eel-98869.upstash.io
      - REDIS_PORT=6379
      - REDIS_PASSWORD=gQAAAAAAAYI1AAIgcDFkZGEzZjlkZDI0MTg0NDQyODgzMjNiYjM4ZTlhNDAzYw
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: always

  worker:
    build: .
    container_name: code-executor-worker
    command: ["node", "dist/worker.js"]
    volumes:
      # Expose host's Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
      - REDIS_HOST=promoted-eel-98869.upstash.io
      - REDIS_PORT=6379
      - REDIS_PASSWORD=gQAAAAAAAYI1AAIgcDFkZGEzZjlkZDI0MTg0NDQyODgzMjNiYjM4ZTlhNDAzYw
      - CONCURRENCY=4
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    restart: always
